<?php

namespace common\models;

use backend\models\ImageUpload;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "categories".
 *
 * @property int $id
 * @property string $name
 * @property int $price_for_1_hour
 * @property string image
 */
class Category extends ActiveRecord
{
    const IMAGE_PATH = 'categories/';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'categories';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['price_for_1_hour'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['image'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'price_for_1_hour' => 'Price For 1 Hour',
            'image' => 'Image'
        ];
    }

    public function getImagePath(): string
    {
        return self::IMAGE_PATH;
    }

    public function saveImage($filename)
    {
        $this->image = $filename;
        return $this->save();
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload($this->imagePath);
        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function getImage()
    {
        if ($this->image) {
            return '/storage/' . $this->imagePath . $this->image;
        }
        return '/storage/' . $this->imagePath . 'no-image-box.png';
    }
}
